# These are supported funding model platforms

github: [NjabuloAI]
patreon: Njabulo 
open_collective: AI
ko_fi: fana
tidelift: Njabulo Jb 
community_bridge: Njabulo Jb AI 
liberapay: Jb
issuehunt: happiness 
otechie: moment 
custom: ["https://example.com/donate"]
